### ISSUE TITLE
How to handle applications that fork with engine_pkcs11?

### ISSUE THREAD

**Issue by nmav** [OpenSC/engine_pkcs11#16]
What is the recommended approach to handle applications that initialize the engine and then fork()? As it is now these applications simply fail to operate. A small example that fails after fork is shown below. Run it as "a.out pkcs11:url PIN"

```
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <string.h>
#include <getopt.h>
#include <err.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <arpa/inet.h>
#include <openssl/bio.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/pkcs7.h>
#include <openssl/err.h>
#include <openssl/engine.h>

int main(int argc, char **argv)
{
	char *private_key_name;
	unsigned char buf[4096];
	EVP_PKEY *private_key;
	EVP_MD_CTX ctx;
	int rc;
	unsigned int sig_len;
	char *key_pass;
	pid_t pid;
	int status = 0;
	ENGINE *e;

	OpenSSL_add_all_algorithms();
	ERR_load_crypto_strings();
	ERR_clear_error();

	ENGINE_load_builtin_engines();

	e = ENGINE_by_id("pkcs11");
	if (!e) abort();


	if (argc < 3) {
		fprintf(stderr, "usage: tool key pass\n");
		exit(1);
	}
	private_key_name = argv[1];
	key_pass = argv[2];


	if (!ENGINE_init(e))
		abort();
	ENGINE_ctrl_cmd_string(e, "PIN", key_pass, 0);
	private_key = ENGINE_load_private_key(e, private_key_name, NULL,
					      NULL);
	if (!private_key)
		abort();

	/* Digest the module data. */
	OpenSSL_add_all_digests();
#if 1
	pid = fork();
	if (pid == -1)
		abort();

	if (pid != 0) {
		waitpid(pid, &status, 0);

		if (WIFEXITED(status)) {
			printf("ok");
			return 0;
		} else {
			return 1;
		}
	}
#endif

	rc = EVP_SignInit(&ctx, EVP_get_digestbyname("SHA1"));
	assert(rc == 1);

	rc = EVP_SignUpdate(&ctx, "hellothere", 8);
	assert(rc == 1);

	sig_len = sizeof(buf);
	rc = EVP_SignFinal(&ctx, buf, &sig_len, private_key);
	assert(rc == 1);
	

	printf("sign-ok\n");

	return 0;
}

```

**Comment by dwmw2** [comment]
What are you testing with? Note that OpenSC is broken w.r.t. behaviour after fork(), and so is p11-kit-proxy.

That said, neither the engine nor libp11 make any attempt to handle fork correctly either. The engine, certainly, should make the bizarre PKCS#11 fork rules transparent to the application. I'm inclined to suspect that libp11 probably should too, and the logic to handle fork() should live there.

We should do something like p11-kit does (the non-deadlocking bits): bump a 'fork counter' in a pthread_atfork() handler in the child, then *if* PKCS#11 functions are called in the child after that, re-initialise the module(s) we're using. And I suppose we'll have to find the object(s) again too, won't we?

I do wonder if we should be migrating towards actually *using* p11-kit for this kind of thing.

**Comment by nmav** [comment]
I was testing with caml-crush mainly, as well as the p11-kit proxy.

The plan looks right. The tricky part would be to get handlers again for all open keys. I'll try to fix the proxy issue.

**Comment by dengert** [comment]
On 6/23/2015 5:44 AM, Nikos Mavrogiannopoulos wrote:
> I was testing with caml-crush mainly, as well as the p11-kit proxy.
>
> The plan looks right. The tricky part would be to get handlers again for all open keys. I'll try to fix the proxy issue.

And may require the PIN again, especially if using a pinpad reader.


>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/16#issuecomment-114441530>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
Patch to libp11 was made, thus issue is resolved (when libp11 is released)
