### ISSUE TITLE
pkcs11_load_public/private_key problem?

### ISSUE THREAD

**Issue by flyingmouse** [OpenSC/engine_pkcs11#17]
I've looked at the code here
https://github.com/OpenSC/engine_pkcs11/blob/master/src/engine_pkcs11.c#L1003
I find that there is no difference between **pkcs11_load_public_key** and **pkcs11_load_private_key**. because whether **isPrivate** is 0 or 1 we execute the same code. Is it a bug? Thanks in advance for your reply.

**Comment by dengert** [comment]
On 6/29/2015 7:01 AM, Haoming Wang
      wrote:
    
    
      I've looked at the code here
        https://github.com/OpenSC/engine_pkcs11/blob/master/src/engine_pkcs11.c#L1003
        I find that there is no difference between pkcs11_load_public_key
        and pkcs11_load_private_key. Is it a bug?
        Thanks in advance for your reply.
    
    
    No, not really.   Look at libp11.c 
    
    214 EVP_PKEY *PKCS11_get_public_key(PKCS11_KEY * key)
    215 {
    216         return PKCS11_get_private_key(key);
    217 }
    
    Line #l1003  in engine_pkcs11.c in effect does the same thing. 
    
    So both do the same thing: return a EVP_PKEY.  In OpenSSL the same
    structure is used for both. 
    
    libp11/src/libp11.h has:
    
     52 /** PKCS11 key object (public or private) */
     53 typedef struct PKCS11_key_st {
     54         char *label;
     55         unsigned char *id;
     56         size_t id_len;
     57         unsigned char isPrivate;        /**< private key
    present? */
     58         unsigned char needLogin;        /**< login to read
    private key? */
     59         EVP_PKEY *evp_key;              /**< initially NULL,
    need to call PKCS11_load_key */
     60         void *_private;
     61 } PKCS11_KEY;
    
    Its confusing,  to say the least.  Smartcards, PKCS#11 and OpenSSL
    have different definitions of what is in a "key".
    
    With a private key, on the smartcard,  one (orthe card driver) may
    have to read the public key to get additional information on the
    key. For RSA, modules and exponent.
    For ECDSA,  EC keys also have the ec parameters, which may or may
    not be considered as part of a "key"
    but are needed, so an attempt is made to read the public key to get
    the  ec parameters that may not be present with the private key.
    The SPKI representation of a public key has the EC parameters. 
    
    libp11/src/p11_key.c  tries to get  all the pieces of a key,  which
    may require the reading  the public key to get the modules and
    exponent.
    For some card the OpenSC code may head the cert to get the SPKI to
    then present it as a public key. 
    
    Are you seeing a problem? 
    
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by flyingmouse** [comment]
Thanks @dengert, as you mentioned, PKCS11_KEY struct contains EVP_PKEY which is initially NULL and then initialised by **priv->ops->get_private()** which converts the obtained pkcs11 struct to the openssl struct EVP_PKEY.  So one more question, maybe a little stupid, the type of the returned value is * **EVP_PKEY**, this struct is defined in openssl/evp.h as 
(ref: http://filezilla.cvs.sourceforge.net/filezilla/FileZilla%20Server/source/includes/openssl/evp.h)
struct evp_pkey_st
	{
	int type;
	int save_type;
	int references;
	union	{
		char *ptr;
#ifndef OPENSSL_NO_RSA
		struct rsa_st *rsa;	/* RSA */
#endif
#ifndef OPENSSL_NO_DSA
		struct dsa_st *dsa;	/* DSA */
#endif
#ifndef OPENSSL_NO_DH
		struct dh_st *dh;	/* DH */
#endif
#ifndef OPENSSL_NO_EC
		struct ec_key_st *ec;	/* ECC */
#endif
		} pkey;

does this contain the private key information? because I don't want it to get out of the smart card. When I googled its member **rsa_st**, I found this http://docs.huihoo.com/doxygen/openssl/1.0.1c/crypto_2rsa_2rsa_8h_source.html#l00129
and is says "functional reference if 'meth' is ENGINE-provided", does that mean it does not go out?
if not I have to find out a resquest/response way to do the TLS handshake.

**Comment by dengert** [comment]
On 7/1/2015 11:08 AM, Haoming Wang
      wrote:
    
    
      Thanks @dengert,
        as you mentioned, PKCS11_KEY struct contains EVP_PKEY which is
        initially NULL and then initialised by priv->ops->get_private()
        which converts the obtained pkcs11 struct to the openssl struct
        EVP_PKEY. So one more question, maybe a little stupid, the type
        of the returned value is * EVP_PKEY, this
        struct is defined in openssl/evp.h as 
        (ref: http://filezilla.cvs.sourceforge.net/filezilla/FileZilla%20Server/source/includes/openssl/evp.h)
        struct evp_pkey_st
        {
        int type;
        int save_type;
        int references;
        union {
        char ptr;
          #ifndef OPENSSL_NO_RSA
          struct rsa_st *rsa; / RSA /
          #endif
          #ifndef OPENSSL_NO_DSA
          struct dsa_st *dsa; / DSA /
          #endif
          #ifndef OPENSSL_NO_DH
          struct dh_st *dh; / DH /
          #endif
          #ifndef OPENSSL_NO_EC
          struct ec_key_st *ec; / ECC */
        #endif
        } pkey;
      does this contain the private key information? because I don't
        want it to get out of the smart card. When I googled its member
        rsa_st, I found this http://docs.huihoo.com/doxygen/openssl/1.0.1c/crypto_2rsa_2rsa_8h_source.html#l00129
        and is says "functional reference if 'meth' is ENGINE-provided",
        does that mean it does not go out?
        if not I have to find out a resquest/response way to do the TLS
        handshake.
    
    
    It does not contain the private key data. The point of the
    engine_pkcs11 is to provide a way for OpenSSL to have the card do
    the crypto operations  on the card.
    Smartcard do not allow the private key data to be read from the
    card, as that is the point of  having a smartcard. 
    (On some cards it may be possible for the card administrator to read
    the private key, but that is not what the engine_pkcs11 is doing..)
    
    
    
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by flyingmouse** [comment]
Thanks @dengert  this helps a lot !
