### ISSUE TITLE
last release is too old

### ISSUE THREAD

**Issue by nmav** [OpenSC/engine_pkcs11#18]
Hello,
 The last release of this project is 5 years old, and the changes since then are quite significant. Please consider making an official release.

**Comment by gerow** [comment]
Just adding a +1 here. I'm interested in using the PKCS#11 URI support at some point in time.

**Comment by dengert** [comment]
Agreed. Main problem is getting a release that will run on Windows which needs libp11 too and
getting the OpenSC MSI files to include libp11 and engine_pkcs11

Anyone out there that can update the WiX installer to do this and is willing to do this?

https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer


On 8/6/2015 9:11 PM, Mike Gerow wrote:
> Just adding a +1 here. I'm interested in using the PKCS#11 URI support at some point in time.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/18#issuecomment-128562047>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
Doesn't it make sense to separate any source from binary releases?

**Comment by dengert** [comment]
I do not understand the question.
Do you mean, have a seperate release of engine_pkcs11 with libp11 from the OpenSC release?

**Comment by nmav** [comment]
My suggestion was about separating a binary release for windows from any source release. That is, not treat any windows binaries are blockers for a source release.

**Comment by dengert** [comment]
@viktorTarasov  My concern is that people are asking for engine_pkcs11 on Windows, and the OpenSC installer already installs OpenSSL, and could easilly install engine_pkcs11 and libp11. But this has not been done.  Also Jenkins (when it is working) will build the windows MSI even for a pull request and nighhtl builds. This can be very usefull for people who can not build OpenSC on windows. 

I am not the one to make a release, or to update the installer, or Jenkins. I leave that up to other developers.

**Comment by dwmw2** [comment]
FWIW it doesn't appear difficult to build with MinGW on a real computer. And there are a bunch of warnings when you do so.

**Comment by Alestrix** [comment]
+1 here as well
For several hours I'm trying to get openssl to decrypt an SMIME message with the corresponding key being stored on a smartcard and the key to success seems to be that engine_pkcs11.dll file. I do not have the knowledge to compile the dll myself, so a binary download would be greatly appreciated.

**Comment by Alestrix** [comment]
Why has this been closed? Is a readily compiled DLL available somewhere now?

**Comment by nmav** [comment]
A compiled DLL is not part of a release. There will be no binaries released from this project; unless of course, someone volunteers to make and maintain them.
