### ISSUE TITLE
Incompatibility with openssl 1.0+

### ISSUE THREAD

**Issue by pencotts** [OpenSC/engine_pkcs11#2]
Moving from openssl 0.9.8h to openssl 1.0.0.e, using  engine_pkcs11 and libp11 from the opensc project repositories. 

When I try the digest command which is OK with 0.9.8(e.g.): 

    openssl dgst -engine pkcs11 -keyform engine -binary -sha1 -sign 10:a93d76ef41f5bb08f17cff81479a664646f66362 file 

I now get the following errors: 

    3085010592:error:260C0065:engine routines:ENGINE_get_pkey_meth:unimplemented public key method:tb_pkmeth.c:127: 
    3085010592:error:0609D09C:digital envelope routines:INT_CTX_NEW:unsupported algorithm:pmeth_lib.c:164: 

It appears that the openssl engine interface has evolved & engine_pkcs11 is not currently compatible

**Comment by nmav** [comment]
Is that issue with the git version of engine_pkcs11 or the released version?

**Comment by levitte** [comment]
I'm surprised, actually.  This may turn out to be a bug i the ENGINE API, as it has a mechanism to tell if an engine module is too old or not...

**Comment by dengert** [comment]
The git versions as of 9/22/15 of libp11 and engine_pkcs11 when used with openssl veriosn 1.0.2a appears to work. The engine_pkcs11 and libp11 have been updated in recent days. 

PATH=/opt/smartcard/bin:$PATH
export OPENSSL_CONF=/opt/smartcard/admin.card/opt-smartcard-openssl.conf
openssl dgst -engine pkcs11 -keyform engine -binary -sha1 -sign slot_1-id_02 test.data

**Comment by levitte** [comment]
Aha, good to know, thanks.
