### ISSUE TITLE
Segmentation fault when loading engine on El Capitan

### ISSUE THREAD

**Issue by nspassov** [OpenSC/engine_pkcs11#24]
Hi,

I am getting segmentation fault 11 when trying to load the engine on El Capitan 10.11.1. I installed engine_pkcs11 via brew along with the dependencies. I also have OpenSC 0.15.

The following line produces segmentation fault:
`engine dynamic -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/Library/OpenSC/lib/pkcs11/opensc-pkcs11.so`

However, the following line executes ok:
`engine dynamic -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD`

Subsequently trying to make a certificate request again results in segmentation fault.

Any help will be appreciated!

**Comment by nmav** [comment]
What is El Capitan? If you want to report a bug on engine_pkcs11 please use the latest version and  include a reproducer.

**Comment by nspassov** [comment]
El Capitan is Mac OS X. Cloning the latest version from github gave me 
`checking should link static openssl... configure: error: OpenSSL is old and cannot link with its static library`
on ./configure

That's why I installed via brew.

`$ openssl version
OpenSSL 0.9.8zg 14 July 2015`

**Comment by dengert** [comment]
Could be a mismatch of openssl libs.

Use ldd to look at libraries and exec and make sure they are using the same version of libraries.
You may need LD_LIBRARY_PATH= to get things straight.


On 10/26/2015 3:49 PM, nspassov wrote:
> Hi,
>
> I am getting segmentation fault 11 when trying to load the engine on El Capitan 10.11.1. I installed engine_pkcs11 via brew along with the dependencies. I also have OpenSC 0.15.
>
> The following line produces segmentation fault:
> |engine dynamic -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre /Library/OpenSC/lib/pkcs11/opensc-pkcs11.so|
>
> However, the following line executes ok:
> |engine dynamic -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD|
>
> Subsequently trying to make a certificate request results again in segmentation fault.
>
> Any help will be appreciated!
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/24>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by frankmorgner** [comment]
All OpenSSL headers have been removed from El Capitane, but the binaries are still present. @nspassov When you install OpenSSL via brew, you need to make sure that the library you're loading is the library you're building with. You need to set `DYLD_LIBRARY_PATH` accordingly on OS X ( `LD_LIBRARY_PATH` is for Linux)

**Comment by mouse07410** [comment]
> Could be a mismatch of openssl libs.

I concur.

> When you install OpenSSL via brew, you need to make sure that the library you're loading
> is the library you're building with.

I'm using Macports. It installs OpenSSL in /opt/local. So I provide `OPENSSL_CFLAGS = -I/opt/local/include` and `OPENSSL_LIBS = -L/opt/local/lib -lssl -lcrypto` environment variable to tell where the include files are, and where the libraries reside that I want it to use. It seems sufficient to get engine_pkcs11 built correctly and run properly.

> I am curious if anyone else running OS X 10.11.1 has been able to get it working.

Yes I have it running on El Capitan 10.11.2. 

You might want to pull mouse07410/engine_pkcs11 fork, because it enables access to public keys without PIN. If you do that, also pull the latest OpenSC/libp11 master. Same with OPENSSL_CFLAGS and OPENSSL_LIBS.

**Comment by mtrojnar** [comment]
As far as I understand, installing the latest libp11/engine_pkcs11 and building the sources against the same version of OpenSSL fixes this issue.

**Comment by nspassov** [comment]
Thanks everyone for the replies! Got it working after I ran

`brew install engine_pkcs11`

El Capitan 10.11.3
