### ISSUE TITLE
Wiki page for engine needs updating

### ISSUE THREAD

**Issue by dengert** [OpenSC/engine_pkcs11#25]
The page needs updateing because the name of  engine has changed names. 

https://github.com/OpenSC/OpenSC/wiki/Engine-pkcs11-quickstart

**Comment by nmav** [comment]
Thanks for bringing that up. I think I'll update the text in the repository and redirect that page here.

**Comment by dwmw2** [comment]
It's more than the name of the engine (in fact, did that even change at all?). The whole of the complexity documented there can be dropped, or relegated to a 'legacy' section.

Since we use p11-kit-proxy.so by default, and accept PKCS#11 URIs, using engine_pkcs11 is very simple now. No config file is needed, and no special engine configuration.

**Comment by nmav** [comment]
The proxy is not available in all systems yet (my debian doesn't have it for example). I've taken a more neutral way in the README. Please check https://github.com/OpenSC/engine_pkcs11 and let me know of comments.

**Comment by dwmw2** [comment]
That still has a section about 'OpenSSL configuration file', when we don't need that at all on non-legacy systems. It really is this simple:
```
$ openssl smime -sign -engine pkcs11  -keyform engine \
  -inkey 'pkcs11:manufacturer=piv_II;id=%01' \
  -in plaintext -out signed -signer cert.pem
```

I'd suggest *starting* with the simple command, and then adding a section telling the reader that on systems where it's built with p11-kit it should Just Work™ but for legacy systems here's how you add a config file...

**Comment by nmav** [comment]
I don't have this weekend a system I can verify commands with p11-kit-proxy. Please send a PR, or I'll schedule it for sometime within the week.

**Comment by dengert** [comment]
I agree, show the simple example then list the other options, such as pointing at a config file,
and how to specify a specific module, or how to use SPY.


On 11/7/2015 3:08 AM, dwmw2 wrote:
> That still has a section about 'OpenSSL configuration file', when we don't need that at all on non-legacy systems. It really is this simple:
>
> |$ openssl smime -sign -engine pkcs11 -keyform engine \ -inkey 'pkcs11:manufacturer=piv_II;id=%01' \ -in plaintext -out signed -signer cert.pem |
>
> I'd suggest /starting/ with the simple command, and then adding a section telling the reader that on systems where it's built with p11-kit it should Just Work™ but for legacy systems here's how you
> add a config file...
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/25#issuecomment-154663793>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
On 11/7/2015 2:31 AM, dwmw2 wrote:
> It's more than the name of the engine (in fact, did that even change at all?).

It used to be engine_pkcs11.so now it is libpkcs11.so

**Comment by dengert** [comment]
On 11/7/2015 2:31 AM, dwmw2 wrote:
> It's more than the name of the engine (in fact, did that even change at all?).  The whole of the complexity documented there can be dropped, or relegated to a 'legacy' section.

Yes the name changed see https://github.com/OpenSC/engine_pkcs11/commit/0ab5515fffe4df44c7209156f7f829b8727aff0a

I would not call it "Legacy" but "Customization Features".

>
> Since we use p11-kit-proxy.so by default, and accept PKCS#11 URIs, using engine_pkcs11 is very simple now. No config file is needed, and no special engine configuration.

If the system has p11-kit-proxy...

>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/25#issuecomment-154656343>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
I've updated the text to show the commands when the proxy is available, and discuss what is needed when is not.
