### ISSUE TITLE
Extract public key using engine_pkcs11 

### ISSUE THREAD

**Issue by zosocanuck** [OpenSC/engine_pkcs11#26]
Hi,

What is the syntax (if it exists) to extract an RSA or ECDSA public key, in conjunction with openssl command line?

-Ivan

**Comment by dengert** [comment]
#!/bin/sh

OPENSC_PATH=/opt/smartcard/lib
#OPENSC_PATH=/usr/lib
OPENSC_ENGINE=/opt/smartcard/lib
#OPENSC_ENGINE=/usr/lib
export LD_LIBRARY_PATH=$OPENSC_ENGINE

openssl << EOF
engine dynamic -vvvv -pre SO_PATH:$OPENSC_ENGINE/engines/engine_pkcs11.so -pre ID:pkcs11 -pre NO_VCHECK:1 -pre LIST_ADD:1 -pre LOAD  -pre MODULE_PATH:$OPENSC_PATH/opensc-pkcs11.so
pkey -engine pkcs11 -pubin -in slot_1-id_01 -inform engine  -text -pubout -out /tmp/pubkey.pem -outform PEM
EOF

/tmp/pubkey.pem:
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnb1nAmYPPjkCrcOvBwqF6vDnR4uN
iAwcB6JQaKik6i5ZKAezuY/ip3rBcqtEi+fYl/sNXpwUtfN4EIcMH7BYzA==
-----END PUBLIC KEY-----
Public-Key: (256 bit)
pub:
     04:9d:bd:67:02:66:0f:3e:39:02:ad:c3:af:07:0a:
     85:ea:f0:e7:47:8b:8d:88:0c:1c:07:a2:50:68:a8:
     a4:ea:2e:59:28:07:b3:b9:8f:e2:a7:7a:c1:72:ab:
     44:8b:e7:d8:97:fb:0d:5e:9c:14:b5:f3:78:10:87:
     0c:1f:b0:58:cc
ASN1 OID: prime256v1
NIST CURVE: P-256

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnb1nAmYPPjkCrcOvBwqF6vDnR4uN
iAwcB6JQaKik6i5ZKAezuY/ip3rBcqtEi+fYl/sNXpwUtfN4EIcMH7BYzA==
-----END PUBLIC KEY-----
Public-Key: (256 bit)
pub:
     04:9d:bd:67:02:66:0f:3e:39:02:ad:c3:af:07:0a:
     85:ea:f0:e7:47:8b:8d:88:0c:1c:07:a2:50:68:a8:
     a4:ea:2e:59:28:07:b3:b9:8f:e2:a7:7a:c1:72:ab:
     44:8b:e7:d8:97:fb:0d:5e:9c:14:b5:f3:78:10:87:
     0c:1f:b0:58:cc
ASN1 OID: prime256v1
NIST CURVE: P-256


You could also extract the certificate. The public key is then the SPKI subjectPublicKeyInfo.


On 11/22/2015 1:24 PM, Ivan Wallis wrote:
> Hi,
>
> What is the syntax (if it exists) to extract an RSA or ECDSA public key, in conjunction with openssl command line?
>
> -Ivan
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/engine_pkcs11/issues/26>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by zosocanuck** [comment]
Thanks that did the trick.
