### ISSUE TITLE
Request for a Windows building manual

### ISSUE THREAD

**Issue by zosocanuck** [OpenSC/engine_pkcs11#27]
Hi,

Does anyone have any instructions on building engine_pkcs11 and libp11 on Windows besides using cygwin? Anyone have experience with building in a VS2013 environment?  The goal is to build dlls.

**Comment by vletoux** [comment]
for libp11, I just added a pull request to add appveyor support
=> libp11.dll & libp11.lib will be automatically generated

**Comment by vletoux** [comment]
done for engine_pkcs11.
While the PR is being reviewed, you can download the binaries at https://ci.appveyor.com/project/vletoux/engine-pkcs11 => select a job => artificacts
libp11.dll, libp11.lib, engine_pkcs11.lib, engine_pkcs11.dll for both x86 & x64

**Comment by mtrojnar** [comment]
Any volunteer?

**Comment by mtrojnar** [comment]
engine_pkcs11 0.2.1 builds with:
```
nmake -f Makefile.mak
```
I removed the Cygwin build dependencies.
