### ISSUE TITLE
Would like the ability to configure DEFAULT_PKCS11_MODULE

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/engine_pkcs11#36]
Currently I have to manually edit `config.h` to make this:
```
/* p11-kit proxy */
#define DEFAULT_PKCS11_MODULE "/Library/OpenSC/lib/opensc-pkcs11.dylib"
```

It would be nice if either the config script could figure it out by itself, or I could point it at the correct library at the configuration time (rather than editing the config file).

**Comment by dwmw2** [comment]
There is a strong argument to be made that p11-kit-proxy is the only thing that makes sense to be invoked automatically as a *default* module, and that if it's installed properly then it would do the right thing (and invoke OpenSC or whatever you have configured for the application in question).

That said, I'd tolerate a `configure` argument which allows you to specify it rather than only picking it up from p11-kit's pkgconfig.

**Comment by mouse07410** [comment]
I have libp11and p11-kit installed:
```
$ port installed p11-kit
The following ports are currently installed:
  p11-kit @0.22.1_0 (active)
```

Nonetheless, it did not get the required proxy installed. Therefore I think that there must be a config argument that would override the faulty (at least on my Mac OS X system) automatic discovery.

**Comment by mtrojnar** [comment]
Implemented in https://github.com/OpenSC/engine_pkcs11/commit/0d0436e035f48dc049d7865c65f70953adc85966.

**Comment by nmav** [comment]
> Nonetheless, it did not get the required proxy installed. Therefore I think that there must be a config  
> argument that would override the faulty (at least on my Mac OS X system) automatic discovery.

That's more than a bug in the installation of p11-kit in macosx rather than an issue of libp11.

**Comment by mtrojnar** [comment]
An interesting side note:
Until https://github.com/OpenSC/engine_pkcs11/commit/2b38204f22dfa9415b1dcd87614500a0fda29176 broke it (5 Apr 2008 by @alonbl), engine_pkcs11 actually attempted to link libcrypto statically.

**Comment by alonbl** [comment]
What interesting note? nothing should be linked statically, not doing so only resolves issues, not to mention that nothing was actually broken for 7 years!

**Comment by mtrojnar** [comment]
It seemed (at least to me) quite interesting in context of the previous discussion in this thread.  Also, as the current maintainer, I am curious about the original rationale for implementing the functionality you broke.  I am __not__ suggesting that it was a bad idea to break it...
Any ideas?

**Comment by alonbl** [comment]
nothing was broken, not even close, p11-kit was not exist back then, this thread is all about p11-kit which has nothing to do with linking with implementation of engine. if you are current maintainer, please maintain, find root cause, do not violate any best practice.

**Comment by mtrojnar** [comment]
Argh.  I indeed posted in a wrong issue.  I'm so sorry.
The intended issue was https://github.com/OpenSC/libp11/issues/52.

BTW: Do you sincerely believe that it is possible to write a single line of code without violating __any__ best practice?

**Comment by alonbl** [comment]
Good luck!
I see that with this approach nothing good can happen.
Please do not refer me any more.
