### ISSUE TITLE
Unnecessary failure during signing operation

### ISSUE THREAD

**Issue by threatspikeadam** [OpenSC/engine_pkcs11#43]
For an unknown reason, the PKCS11_enumerate_certs() call is failing inside pkcs11_load_key() when I attempt a signing operation using a SafeNet eToken 510x. After downloading the source and removing the check that this enumerate call was successful, the signing completes successfully.  

It seems unnecessary for the enumerate call to succeed given that the only reason this call is made is to print the distinguished names of certificates on the device when in verbose mode.  If there is any opportunity to get the error code from the P11D provider then it would be good to include this also in the pkcs11 error string.

**Comment by mtrojnar** [comment]
I removed the excessive debugging code in https://github.com/OpenSC/libp11/commit/f5274ad23db292978e9346c95e245682d91463ba.

**Comment by threatspikeadam** [comment]
Thank you :)
